//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRON_PROGRAMMER_BOT_Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRON_PROGRAMMER_BOT_Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] AI {
            get {
                object obj = ResourceManager.GetObject("AI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;u&gt;У тебя есть возможность для &lt;b&gt;{counter}&lt;/b&gt; вопросов!&lt;/u&gt;.
        /// </summary>
        public static string CommonQuestionPageAttempts {
            get {
                return ResourceManager.GetString("CommonQuestionPageAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _**Это заключительный ответ. Попыток больше нет!!!**_.
        /// </summary>
        public static string CommonQuestionPageFinalTrying {
            get {
                return ResourceManager.GetString("CommonQuestionPageFinalTrying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _**Осталась возможность только для 1 вопроса!!!**_.
        /// </summary>
        public static string CommonQuestionPagePenultimateQuestion {
            get {
                return ResourceManager.GetString("CommonQuestionPagePenultimateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonQuestionsPage.
        /// </summary>
        public static string CommonQuestionsPage {
            get {
                return ResourceManager.GetString("CommonQuestionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **_Задавайте свой вопрос_**
        ///
        ///**У тебя есть возможность задать вопросы не более 3 раз!**
        ///
        ///_Важно задать вопрос очень конкретно и по теме!_
        ///                                      .
        /// </summary>
        public static string CommonQuestionsPageText {
            get {
                return ResourceManager.GetString("CommonQuestionsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectWithManagerPage.
        /// </summary>
        public static string ConnectWithManagerPage {
            get {
                return ResourceManager.GetString("ConnectWithManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;u&gt;Обращение к сотрудникам школы!&lt;/u&gt;&lt;/b&gt;
        ///Задавайте свой вопрос 
        ///&lt;u&gt;Мы вернемся с обратной связью в ближайшее время!&lt;/u&gt;
        ///&lt;b&gt;Спасибо за Ваш интерес!&lt;/b&gt;.
        /// </summary>
        public static string ConnectWithManagerPageText {
            get {
                return ResourceManager.GetString("ConnectWithManagerPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Возможностей задавать вопросы больше нет...увы**.
        /// </summary>
        public static string CoomQuestionPageStopAI {
            get {
                return ResourceManager.GetString("CoomQuestionPageStopAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeepLinksPage.
        /// </summary>
        public static string DeepLinksPage {
            get {
                return ResourceManager.GetString("DeepLinksPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] FeedBack {
            get {
                object obj = ResourceManager.GetObject("FeedBack", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ironprogrammer.ru/#rec460811109.
        /// </summary>
        public static string GoToSchool {
            get {
                return ResourceManager.GetString("GoToSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты главный специалист по C# в мире. Ответь на вопрос четко, структурированно, но кратко, укладываясь в 1000 символов..
        /// </summary>
        public static string HeaderPromtForAI {
            get {
                return ResourceManager.GetString("HeaderPromtForAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpByCoursePage.
        /// </summary>
        public static string HelpByCoursePage {
            get {
                return ResourceManager.GetString("HelpByCoursePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;u&gt;Онлайн консультация!&lt;/u&gt;&lt;/b&gt;
        ///
        ///Получение ответа на вопрос
        ///Ты находишься в разделе получения информации по интересующему вопросу
        ///
        ///&lt;u&gt;&lt;i&gt;В этом разделе помогает мощный интелект всемирной паутины😊&lt;/i&gt;&lt;/u&gt;
        ///
        ///Выбери , пожалуйста, какого &lt;em&gt;формата&lt;/em&gt; у тебя вопрос и тебе обязательно помогут.
        ///
        ///&lt;b&gt;Совет: спрашивай общее направление, пытайся до глубины задачи дойти сам!&lt;/b&gt;❗️
        ///Успехов!.
        /// </summary>
        public static string HelpByCoursePageText {
            get {
                return ResourceManager.GetString("HelpByCoursePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoByCoursePage.
        /// </summary>
        public static string InfoByCoursePage {
            get {
                return ResourceManager.GetString("InfoByCoursePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Информация о курсах!&lt;/b&gt;  Вы можете перейти на страницу школы &lt;b&gt;&lt;u&gt;IRON PROGRAMMER&lt;/u&gt;&lt;/b&gt;.
        /// </summary>
        public static string InfoByCoursePageText {
            get {
                return ResourceManager.GetString("InfoByCoursePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] PhotoAI {
            get {
                object obj = ResourceManager.GetObject("PhotoAI", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolveTaskPage.
        /// </summary>
        public static string ResolveTaskPage {
            get {
                return ResourceManager.GetString("ResolveTaskPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Решение задачи! 💻**
        ///
        ///_**Задавайте свой вопрос**_
        ///
        ///**У тебя есть возможность задать один вопрос!**
        ///
        ///_Не спрашивай решение, спроси направление_
        ///
        ///_Рекомендую спрашивать по следующему образцу: что я делаю не так? краткое условие задачи:  мой код:   _.
        /// </summary>
        public static string ResolveTaskPageText {
            get {
                return ResourceManager.GetString("ResolveTaskPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendQuastion.
        /// </summary>
        public static string SendQuastion {
            get {
                return ResourceManager.GetString("SendQuastion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **Привет!**
        ///
        ///**Рад видеть тебя😊**
        ///
        ///_Задай свой вопрос и я тебе обязательно отвечу!_
        ///
        ///Хочешь получить помощь по курсу?
        ///Хочешь узнать о нашей школе и курсах или получить консультацию от наших специалистов?
        ///Нажми одну из *кнопок* ниже, выбирай направление - я отвечу и помогу тебе😉.
        /// </summary>
        public static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ты главный специалист по C# в мире. Ответь на вопрос четко, структурированно, но кратко, укладываясь в 1000 символов, не давать все решение, а только строку!(это важно), которую надо либо поменять, либо поправить, либо объяснить!!!.
        /// </summary>
        public static string TaskPromt {
            get {
                return ResourceManager.GetString("TaskPromt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ThinlingAI {
            get {
                object obj = ResourceManager.GetObject("ThinlingAI", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
