//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRON_PROGRAMMER_BOT_Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRON_PROGRAMMER_BOT_Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CommonQuestionsPage.
        /// </summary>
        public static string CommonQuestionsPage {
            get {
                return ResourceManager.GetString("CommonQuestionsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;u&gt;Задавайте свой вопрос&lt;/u&gt;&lt;/b&gt;.
        /// </summary>
        public static string CommonQuestionsPageText {
            get {
                return ResourceManager.GetString("CommonQuestionsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectWithManagerPage.
        /// </summary>
        public static string ConnectWithManagerPage {
            get {
                return ResourceManager.GetString("ConnectWithManagerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;u&gt;Обращение к сотрудникам школы!&lt;/u&gt;&lt;/b&gt;
        ///Задавайте свой вопрос 
        ///&lt;u&gt;Мы вернемся с обратной связью в ближайшее время!&lt;/u&gt;
        ///&lt;b&gt;Спасибо за Ваш интерес!&lt;/b&gt;.
        /// </summary>
        public static string ConnectWithManagerPageText {
            get {
                return ResourceManager.GetString("ConnectWithManagerPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://ironprogrammer.ru/#rec460811109.
        /// </summary>
        public static string GoToSchool {
            get {
                return ResourceManager.GetString("GoToSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HelpByCoursePage.
        /// </summary>
        public static string HelpByCoursePage {
            get {
                return ResourceManager.GetString("HelpByCoursePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;&lt;u&gt;Онлайн консультация!&lt;/u&gt;&lt;/b&gt;
        ///
        ///Получение ответа на вопрос
        ///Ты находишься в разделе получения информации по интересующему вопросу
        ///
        ///&lt;u&gt;&lt;i&gt;В этом разделе помогает мощный интелект всемирной паутины😊&lt;/i&gt;&lt;/u&gt;
        ///
        ///Выбери , пожалуйста, какого &lt;em&gt;формата&lt;/em&gt; у тебя вопрос и тебе обязательно помогут.
        ///
        ///&lt;b&gt;Совет: спрашивай общее направление, пытайся до глубины задачи дойти сам!&lt;/b&gt;❗️
        ///Успехов!.
        /// </summary>
        public static string HelpByCoursePageText {
            get {
                return ResourceManager.GetString("HelpByCoursePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfoByCoursePage.
        /// </summary>
        public static string InfoByCoursePage {
            get {
                return ResourceManager.GetString("InfoByCoursePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Информация о курсах!&lt;/b&gt;  Вы можете перейти на страницу школы &lt;b&gt;&lt;u&gt;IRON PROGRAMMER&lt;/u&gt;&lt;/b&gt;.
        /// </summary>
        public static string InfoByCoursePageText {
            get {
                return ResourceManager.GetString("InfoByCoursePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ResolveTaskPage.
        /// </summary>
        public static string ResolveTaskPage {
            get {
                return ResourceManager.GetString("ResolveTaskPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Решение задачи! 💻&lt;/b&gt;
        ///&lt;u&gt;&lt;i&gt;Отправьте , пожалуйста:&lt;/i&gt;&lt;/u&gt;
        ///&lt;i&gt; - ссылку на задачу&lt;/i&gt;
        ///&lt;i&gt; - ссылку на Ваше решение&lt;/i&gt;
        ///&lt;i&gt; - Ваш вопрос&lt;/i&gt;.
        /// </summary>
        public static string ResolveTaskPageText {
            get {
                return ResourceManager.GetString("ResolveTaskPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendQuastion.
        /// </summary>
        public static string SendQuastion {
            get {
                return ResourceManager.GetString("SendQuastion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Привет!&lt;/b&gt;
        ///&lt;b&gt;Рад видеть тебя😊&lt;/b&gt;
        ///
        ///&lt;u&gt;Задай свой вопрос и я тебе обязательно отвечу!&lt;/u&gt;
        ///
        ///Хочешь получить помощь по курсу?
        ///Хочешь узнать о нашей школе и курсах или получить консультацию от наших специалистов?
        ///Нажми одну из &lt;em&gt;кнопок&lt;/em&gt; ниже, выбирай направление - я отвечу и помогу тебе😉.
        /// </summary>
        public static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
    }
}
